# Generated by Django 4.2.13 on 2024-06-18 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Заполните ФИО')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Введите почту')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Номер телефона')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
